# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image for building the server
FROM node:18-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire source code into the working directory
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a smaller Node.js image for the runtime
FROM node:18-slim

# Set the working directory in the runtime image
WORKDIR /app

# Copy the build files from the builder image
COPY --from=builder /app/build ./build

# Copy package.json and package-lock.json for production install
COPY package.json package-lock.json ./

# Install only production dependencies
RUN npm install --omit=dev

# Set environment variables for Twitter API
ENV CLIENT_ID=your_client_id_here
ENV CLIENT_SECRET=your_client_secret_here
ENV BEARER_TOKEN=your_bearer_token_here
ENV ACCESS_TOKEN=your_access_token_here
ENV REFRESH_TOKEN=your_refresh_token_here

# Start the server
CMD ["node", "build/index.js"]